apiVersion: v1
kind: pod
metadata:
  name: helloworld
  lablels:
      app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: arjunachari12/k8s-demo
  ports:
  - name: demo-pod-port
    containerPort: 3000
