apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    role: helloworld
spec:
  containers:
    - name: hellocontainer
      image: arjunachari12/k8s-demo
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP
